spring.application.name=AgroHub
server.port=8081

# Параметры подключения
spring.datasource.url=jdbc:postgresql://localhost:5432/agrohub
spring.datasource.username=mironnaidanov
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Чтобы Hibernate не ругался на отсутствие схем в новых версиях
spring.jpa.generate-ddl=true